name: Cypress Tests
run-name: Cypress tests in ${{ inputs.browser || 'chrome'}}

on:
  push:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Please select a browser for test run'
        required: true
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          retries: 2
          browser: ${{ inputs.browser || 'chrome'}}
